name: JS Testing

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm install

      - name: Build JS and CSS assets
        run: npm run dev
